[package]
name = "ra_unsafe"
version = "0.1.0"
authors = ["Vurv <56230599+Vurv78@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
detour = { version = "0.8.0", default-features = false }
